export const champions = [
  {
    id: "lux",
    name: "Lux",
    title: "Lady of Luminosity",
    roles: ["Mage", "Support"],
    region: "Demacia",
    imageUrl: "/champions/lux.jpeg",
    backgroundImage: "/backgrounds/lux-bg.jpeg",
    theme: {
      primary: "#88C9F9",
      secondary: "#FFD700",
      accent: "#F0E6D2",
      overlay: "rgba(30, 30, 46, 0.75)",
    },
  },
  {
    id: "ahri",
    name: "Ahri",
    title: "Nine-Tailed Fox",
    roles: ["Mage", "Assassin"],
    region: "Ionia",
    imageUrl: "/champions/ahri.jpeg",
    backgroundImage: "/backgrounds/ahri-bg.jpeg",
    theme: {
      primary: "#FF69B4",
      secondary: "#87CEEB",
      accent: "#DDA0DD",
      overlay: "rgba(30, 30, 46, 0.75)",
    },
  },
  {
    id: "yasuo",
    name: "Yasuo",
    title: "The Unforgiven",
    roles: ["Fighter", "Assassin"],
    region: "Ionia",
    imageUrl:
      "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yasuo_0.jpg",
    backgroundImage:
      "https://images.contentstack.io/v3/assets/blt187521ff0727be24/blt41c476486b063ef8/60ee13df31f9ee2ab09ec0f4/yasuo-splash.jpg",
    theme: {
      primary: "#907A4A",
      secondary: "#4A6670",
      accent: "#C89B3C",
      overlay: "rgba(30, 30, 46, 0.75)",
    },
  },
  {
    id: "jinx",
    name: "Jinx",
    title: "The Loose Cannon",
    roles: ["Marksman"],
    region: "Piltover & Zaun",
    imageUrl:
      "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jinx_0.jpg",
    backgroundImage:
      "https://images.contentstack.io/v3/assets/blt731acb42bb3d1659/blt0f99c9524f7b0025/626c74c3e73ffb4ff1f0e64f/051022_ASC_2022_Comedown_Banner_no-title.jpg",
    theme: {
      primary: "#FF1E54",
      secondary: "#00ABFF",
      accent: "#FF69B4",
      overlay: "rgba(30, 30, 46, 0.75)",
    },
  },
  {
    id: "zed",
    name: "Zed",
    title: "The Master of Shadows",
    roles: ["Assassin"],
    region: "Ionia",
    imageUrl: "/champions/zed.jpeg",
    backgroundImage: "/backgrounds/zed-bg.jpeg",
    theme: {
      primary: "#FF0000",
      secondary: "#4A4A4A",
      accent: "#8B0000",
      overlay: "rgba(30, 30, 46, 0.75)",
    },
  },
  {
    id: "kaisa",
    name: "Kai'Sa",
    title: "Daughter of the Void",
    roles: ["Marksman"],
    region: "Void",
    imageUrl: "/champions/kaisa.jpeg",
    backgroundImage: "/backgrounds/kaisa-bg.jpeg",
    theme: {
      primary: "#8A2BE2",
      secondary: "#4B0082",
      accent: "#9370DB",
      overlay: "rgba(30, 30, 46, 0.75)",
    },
  },
  {
    id: "lee-sin",
    name: "Lee Sin",
    title: "The Blind Monk",
    roles: ["Fighter", "Assassin"],
    region: "Ionia",
    imageUrl: "/champions/leesin.jpeg",
    backgroundImage: "/backgrounds/leesin-bg.jpeg",
    theme: {
      primary: "#CD853F",
      secondary: "#8B4513",
      accent: "#DAA520",
      overlay: "rgba(30, 30, 46, 0.75)",
    },
  },
  {
    id: "thresh",
    name: "Thresh",
    title: "The Chain Warden",
    roles: ["Support", "Tank"],
    region: "Shadow Isles",
    imageUrl: "/champions/thresh.jpeg",
    backgroundImage: "/backgrounds/thresh-bg.jpeg",
    theme: {
      primary: "#50C878",
      secondary: "#006400",
      accent: "#98FF98",
      overlay: "rgba(30, 30, 46, 0.75)",
    },
  },
  {
    id: "yone",
    name: "Yone",
    title: "The Unforgotten",
    roles: ["Fighter", "Assassin"],
    region: "Ionia",
    imageUrl: "/champions/yone.jpeg",
    backgroundImage: "/backgrounds/yone-bg.jpeg",
    theme: {
      primary: "#483D8B",
      secondary: "#191970",
      accent: "#6A5ACD",
      overlay: "rgba(30, 30, 46, 0.75)",
    },
  },
  {
    id: "pyke",
    name: "Pyke",
    title: "The Bloodharbor Ripper",
    roles: ["Support", "Assassin"],
    region: "Bilgewater",
    imageUrl: "/champions/pyke.jpeg",
    backgroundImage: "/backgrounds/pyke-bg.jpeg",
    theme: {
      primary: "#00688B",
      secondary: "#104E8B",
      accent: "#1E90FF",
      overlay: "rgba(30, 30, 46, 0.75)",
    },
  },
  {
    id: "vayne",
    name: "Vayne",
    title: "The Night Hunter",
    roles: ["Marksman"],
    region: "Demacia",
    imageUrl: "/champions/vayne.jpeg",
    backgroundImage: "/backgrounds/vayne-bg.jpeg",
    theme: {
      primary: "#4A0404",
      secondary: "#800000",
      accent: "#8B0000",
      overlay: "rgba(30, 30, 46, 0.75)",
    },
  },
  {
    id: "akali",
    name: "Akali",
    title: "The Rogue Assassin",
    roles: ["Assassin"],
    region: "Ionia",
    imageUrl: "/champions/akali.jpeg",
    backgroundImage: "/backgrounds/akali-bg.jpeg",
    theme: {
      primary: "#00FF7F",
      secondary: "#2E8B57",
      accent: "#98FB98",
      overlay: "rgba(30, 30, 46, 0.75)",
    },
  },
  {
    id: "irelia",
    name: "Irelia",
    title: "The Blade Dancer",
    roles: ["Fighter", "Assassin"],
    region: "Ionia",
    imageUrl: "/champions/irelia.jpeg",
    backgroundImage: "/backgrounds/irelia-bg.jpeg",
    theme: {
      primary: "#4169E1",
      secondary: "#000080",
      accent: "#1E90FF",
      overlay: "rgba(30, 30, 46, 0.75)",
    },
  },
  {
    id: "jhin",
    name: "Jhin",
    title: "The Virtuoso",
    roles: ["Marksman"],
    region: "Ionia",
    imageUrl: "/champions/jhin.jpeg",
    backgroundImage: "/backgrounds/jhin-bg.jpeg",
    theme: {
      primary: "#8B4513",
      secondary: "#A0522D",
      accent: "#CD853F",
      overlay: "rgba(30, 30, 46, 0.75)",
    },
  },
  {
    id: "kayn",
    name: "Kayn",
    title: "The Shadow Reaper",
    roles: ["Fighter", "Assassin"],
    region: "Ionia",
    imageUrl: "/champions/kayn.jpeg",
    backgroundImage: "/backgrounds/kayn-bg.jpeg",
    theme: {
      primary: "#8B008B",
      secondary: "#4B0082",
      accent: "#9400D3",
      overlay: "rgba(30, 30, 46, 0.75)",
    },
  },
  {
    id: "katarina",
    name: "Katarina",
    title: "The Sinister Blade",
    roles: ["Assassin"],
    region: "Noxus",
    imageUrl: "/champions/katarina.jpeg",
    backgroundImage: "/backgrounds/katarina-bg.jpeg",
    theme: {
      primary: "#DC143C",
      secondary: "#8B0000",
      accent: "#FF0000",
      overlay: "rgba(30, 30, 46, 0.75)",
    },
  },
  {
    id: "samira",
    name: "Samira",
    title: "The Desert Rose",
    roles: ["Marksman"],
    region: "Noxus",
    imageUrl: "/champions/samira.jpeg",
    backgroundImage: "/backgrounds/samira-bg.jpeg",
    theme: {
      primary: "#CD5C5C",
      secondary: "#8B0000",
      accent: "#FF4500",
      overlay: "rgba(30, 30, 46, 0.75)",
    },
  },
  {
    id: "sylas",
    name: "Sylas",
    title: "The Unshackled",
    roles: ["Mage", "Fighter"],
    region: "Demacia",
    imageUrl: "/champions/sylas.jpeg",
    backgroundImage: "/backgrounds/sylas-bg.jpeg",
    theme: {
      primary: "#4682B4",
      secondary: "#191970",
      accent: "#4169E1",
      overlay: "rgba(30, 30, 46, 0.75)",
    },
  },
  {
    id: "zoe",
    name: "Zoe",
    title: "The Aspect of Twilight",
    roles: ["Mage"],
    region: "Targon",
    imageUrl: "/champions/zoe.jpeg",
    backgroundImage: "/backgrounds/zoe-bg.jpeg",
    theme: {
      primary: "#FF69B4",
      secondary: "#FF1493",
      accent: "#FFB6C1",
      overlay: "rgba(30, 30, 46, 0.75)",
    },
  },
  {
    id: "aatrox",
    name: "Aatrox",
    title: "The Darkin Blade",
    roles: ["Fighter", "Tank"],
    region: "Runeterra",
    imageUrl: "/champions/aatrox.jpeg",
    backgroundImage: "/backgrounds/aatrox-bg.jpeg",
    theme: {
      primary: "#8B0000",
      secondary: "#800000",
      accent: "#B22222",
      overlay: "rgba(30, 30, 46, 0.75)",
    },
  },
];
